In [3]:
import pandas as pd
import numpy as np 
import requests
from io import StringIO

In [5]:
df_clientes = pd.read_excel(r'C:\Users\fedec\OneDrive\Desktop\contenido\py\DS\CASO PRÁCTICO 1\Practica-creo-Dataset\Clientes.xlsx',sheet_name = "Sheet1")
df_clientes

,ID Cliente,Nombre cliente,Segmento,País,Ciudad,Estado,Código Postal,Región
0,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South
1,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West
2,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South
3,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West
4,AA-10480,Andrew Allen,Consumer,United States,Concord,North Carolina,28027.0,South
...,...,...,...,...,...,...,...,...
788,CJ-11875,Carl Jackson,Corporate,Romania,NaN,NaN,NaN,NaN
789,RS-19870,Roy Skaria,Home Office,Romania,NaN,NaN,NaN,NaN
790,SC-20845,Sung Chung,Consumer,Romania,NaN,NaN,NaN,NaN
791,RE-19405,Ricardo Emerson,Consumer,Romania,NaN,NaN,NaN,NaN
792,SM-20905,Susan MacKendrick,Consumer,Romania,NaN,NaN,NaN,NaN

In [7]:
df_Productos = pd.read_excel(r'C:\Users\fedec\OneDrive\Desktop\contenido\py\DS\CASO PRÁCTICO 1\Practica-creo-Dataset\Productos.xlsx',sheet_name = "Sheet1")
df_Productos

,ID Producto,Categoría,Sub-categoría,Nombre Producto,Coste Producción
0,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,230.098156
1,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",563.102730
2,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,11.746474
3,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,608.528822
4,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,12.728871
...,...,...,...,...,...
1859,TEC-MA-10003589,Technology,Machines,Cisco 8961 IP Phone Charcoal,212.190300
1860,OFF-AP-10003099,Office Supplies,Appliances,"Eureka Hand Vacuum, Bagless",124.048834
1861,TEC-PH-10002645,Technology,Phones,LG G2,869.947650
1862,OFF-ST-10001627,Office Supplies,Storage,Eldon Jumbo ProFile Portable File Boxes Graphi...,35.736686
1863,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,390.302725

In [9]:
df_ventas = pd.read_excel(r'C:\Users\fedec\OneDrive\Desktop\contenido\py\DS\CASO PRÁCTICO 1\Practica-creo-Dataset\Ventas.xlsx',sheet_name = "Sheet1")
df_ventas

,ID Pedido,Fecha compra,Fecha envío,Modo envío,ID Cliente,ID Producto,Precio unitario,Cantidad
0,CA-2016-152156,2020-11-08,2020-11-11 05:00:00,Second Class,CG-12520,FUR-BO-10001798,"261,96",2
1,CA-2016-152156,2020-11-08,2020-11-11 00:00:00,Second Class,CG-12520,FUR-CH-10000454,"731,94",3
2,CA-2016-138688,2020-06-12,2020-06-16 00:00:00,Second Class,DV-13045,OFF-LA-10000240,"14,62",2
3,US-2015-108966,2019-10-11,NaT,Standard Class,SO-20335,FUR-TA-10000577,"957,5775",5
4,US-2015-108966,2019-10-11,2019-10-18 00:00:00,Standard Class,SO-20335,OFF-ST-10000760,"22,368",2
...,...,...,...,...,...,...,...,...
9989,CA-2014-110422,2018-01-21,2018-01-23 00:00:00,Second Class,TB-21400,FUR-FU-10001889,"25,248",3
9990,CA-2017-121258,2021-02-26,2021-03-03 00:00:00,Standard Class,DB-13060,FUR-FU-10000747,"91,96",2
9991,CA-2017-121258,2021-02-26,2021-03-03 00:00:00,Standard Class,DB-13060,TEC-PH-10003645,"258,576",2
9992,CA-2017-121258,2021-02-26,2021-03-03 00:00:00,Standard Class,DB-13060,OFF-PA-10004041,"29,6",4
9993,CA-2017-119914,2021-05-04,2021-05-09 00:00:00,Second Class,CC-12220,OFF-AP-10002684,"243,16",2

In [10]:
df_clientes.isnull().sum()

ID Cliente          0
Nombre cliente      0
Segmento            0
País                0
Ciudad            455
Estado            455
Código Postal     455
Región            455
dtype: int64

In [13]:
df_Productos.isnull().sum()

ID Producto         0
Categoría           0
Sub-categoría       0
Nombre Producto     1
Coste Producción    2
dtype: int64

In [15]:
df_ventas.isnull().sum()

ID Pedido          0
Fecha compra       3
Fecha envío        6
Modo envío         0
ID Cliente         0
ID Producto        0
Precio unitario    0
Cantidad           0
dtype: int64

In [17]:
# Eliminar filas donde 'Fecha compra' es nulo
df_ventas = df_ventas.dropna(subset=["Fecha compra"])

Genero Percentil

In [20]:

ventas_ayores  = df_ventas[df_ventas["Cantidad"] > 13]

ventas_ayores.count()

ID Pedido          29
Fecha compra       29
Fecha envío        29
Modo envío         29
ID Cliente         29
ID Producto        29
Precio unitario    29
Cantidad           29
dtype: int64

In [22]:
cantidades = df_ventas[df_ventas["Cantidad"] > 13].index
df_ventas = df_ventas.drop(cantidades)
df_ventas

,ID Pedido,Fecha compra,Fecha envío,Modo envío,ID Cliente,ID Producto,Precio unitario,Cantidad
0,CA-2016-152156,2020-11-08,2020-11-11 05:00:00,Second Class,CG-12520,FUR-BO-10001798,"261,96",2
1,CA-2016-152156,2020-11-08,2020-11-11 00:00:00,Second Class,CG-12520,FUR-CH-10000454,"731,94",3
2,CA-2016-138688,2020-06-12,2020-06-16 00:00:00,Second Class,DV-13045,OFF-LA-10000240,"14,62",2
3,US-2015-108966,2019-10-11,NaT,Standard Class,SO-20335,FUR-TA-10000577,"957,5775",5
4,US-2015-108966,2019-10-11,2019-10-18 00:00:00,Standard Class,SO-20335,OFF-ST-10000760,"22,368",2
...,...,...,...,...,...,...,...,...
9989,CA-2014-110422,2018-01-21,2018-01-23 00:00:00,Second Class,TB-21400,FUR-FU-10001889,"25,248",3
9990,CA-2017-121258,2021-02-26,2021-03-03 00:00:00,Standard Class,DB-13060,FUR-FU-10000747,"91,96",2
9991,CA-2017-121258,2021-02-26,2021-03-03 00:00:00,Standard Class,DB-13060,TEC-PH-10003645,"258,576",2
9992,CA-2017-121258,2021-02-26,2021-03-03 00:00:00,Standard Class,DB-13060,OFF-PA-10004041,"29,6",4
9993,CA-2017-119914,2021-05-04,2021-05-09 00:00:00,Second Class,CC-12220,OFF-AP-10002684,"243,16",2

Completo las fechas de envio que se encuentran vacias

In [25]:
df_ventas["Fecha compra"] = pd.to_datetime(df_ventas["Fecha compra"])
df_ventas["Fecha envío"] = pd.to_datetime(df_ventas["Fecha envío"])

In [27]:
df_ventas["Fecha envío"].dtype

dtype('<M8[ns]')

In [29]:
fechas_resto = df_ventas["Fecha envío"] - df_ventas["Fecha compra"]
fechas_resto = fechas_resto.dt.days
medias_dias = fechas_resto.mean()

In [31]:
def Reemplazo_NA(x):
    if pd.isna(x):
        return df_ventas["Fecha compra"].iloc[0] + pd.to_timedelta(medias_dias,unit='D')
    return x

In [33]:
df_ventas["Fecha envío"] = df_ventas["Fecha envío"].apply(Reemplazo_NA)

print(df_ventas["Fecha envío"])

0      2020-11-11 05:00:00.000000000
1      2020-11-11 00:00:00.000000000
2      2020-06-16 00:00:00.000000000
3      2020-11-11 22:58:57.806347926
4      2019-10-18 00:00:00.000000000
                    ...
9989   2018-01-23 00:00:00.000000000
9990   2021-03-03 00:00:00.000000000
9991   2021-03-03 00:00:00.000000000
9992   2021-03-03 00:00:00.000000000
9993   2021-05-09 00:00:00.000000000
Name: Fecha envío, Length: 9962, dtype: datetime64[ns]

transformo en INT

In [36]:
df_ventas["Precio unitario"] = df_ventas["Precio unitario"].str.replace(',','')
df_ventas["Precio unitario"] = pd.to_numeric(df_ventas["Precio unitario"],errors = 'coerce')

In [38]:
df_Productos["Coste Producción"] = pd.to_numeric(df_Productos["Coste Producción"],errors = 'coerce')

In [40]:
m1 = df_clientes.merge(df_ventas, on="ID Cliente",how="inner")
m1

,ID Cliente,Nombre cliente,Segmento,País,Ciudad,Estado,Código Postal,Región,ID Pedido,Fecha compra,Fecha envío,Modo envío,ID Producto,Precio unitario,Cantidad
0,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,CA-2016-152156,2020-11-08,2020-11-11 05:00:00,Second Class,FUR-BO-10001798,26196,2
1,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,CA-2016-152156,2020-11-08,2020-11-11 00:00:00,Second Class,FUR-CH-10000454,73194,3
2,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,CA-2017-164098,2021-01-26,2021-01-27 00:00:00,First Class,OFF-ST-10000615,1816,2
3,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,US-2015-123918,2019-10-15,2019-10-15 00:00:00,Same Day,FUR-FU-10004952,131376,6
4,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,US-2015-123918,2019-10-15,2019-10-15 00:00:00,Same Day,OFF-PA-10003001,5344,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9957,SM-20905,Susan MacKendrick,Consumer,Romania,NaN,NaN,NaN,NaN,CA-2016-129280,2020-05-03,2020-05-05 00:00:00,First Class,OFF-ST-10002554,19564,5
9958,SM-20905,Susan MacKendrick,Consumer,Romania,NaN,NaN,NaN,NaN,CA-2016-129280,2020-05-03,2020-05-05 00:00:00,First Class,FUR-FU-10001876,51968,2
9959,SM-20905,Susan MacKendrick,Consumer,Romania,NaN,NaN,NaN,NaN,CA-2016-129280,2020-05-03,2020-05-05 00:00:00,First Class,TEC-AC-10002637,431976,3
9960,SM-20905,Susan MacKendrick,Consumer,Romania,NaN,NaN,NaN,NaN,CA-2016-129280,2020-05-03,2020-05-05 00:00:00,First Class,TEC-MA-10003589,224937,3
9961,SM-20905,Susan MacKendrick,Consumer,Romania,NaN,NaN,NaN,NaN,CA-2016-129280,2020-05-03,2020-05-05 00:00:00,First Class,OFF-LA-10000081,6,2

In [42]:
df_global = df_Productos.merge(m1, on="ID Producto",how="inner")
df_global

,ID Producto,Categoría,Sub-categoría,Nombre Producto,Coste Producción,ID Cliente,Nombre cliente,Segmento,País,Ciudad,Estado,Código Postal,Región,ID Pedido,Fecha compra,Fecha envío,Modo envío,Precio unitario,Cantidad
0,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,230.098156,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,CA-2016-152156,2020-11-08,2020-11-11 05:00:00,Second Class,26196,2
1,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,230.098156,AG-10900,Arthur Gainer,Consumer,United States,Tucson,Arizona,85705.0,West,CA-2017-110198,2021-05-01,2021-05-02 00:00:00,First Class,314352,3
2,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,230.098156,SV-20365,Seth Vernon,Consumer,United States,Dover,Delaware,19901.0,East,CA-2017-159793,2021-08-25,2021-08-29 00:00:00,Standard Class,13098,2
3,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,230.098156,HF-14995,Herbert Flentye,Consumer,Germany,NaN,NaN,NaN,NaN,CA-2016-117681,2020-04-09,2020-04-14 00:00:00,Standard Class,556665,5
4,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",563.102730,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,CA-2016-152156,2020-11-08,2020-11-11 00:00:00,Second Class,73194,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9966,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,390.302725,KF-16285,Karen Ferguson,Home Office,Spain,NaN,NaN,NaN,NaN,US-2017-148362,2021-07-01,2021-07-08 00:00:00,Standard Class,16999,1
9967,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,390.302725,GM-14695,Greg Maxwell,Corporate,Spain,NaN,NaN,NaN,NaN,CA-2016-100244,2020-09-20,2020-09-24 00:00:00,Standard Class,271984,2
9968,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,390.302725,CM-12235,Chris McAfee,Consumer,Spain,NaN,NaN,NaN,NaN,CA-2016-144309,2020-12-10,2020-12-16 00:00:00,Standard Class,67996,5
9969,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,390.302725,LB-16795,Laurel Beltran,Home Office,Spain,NaN,NaN,NaN,NaN,CA-2017-147032,2021-07-31,2021-08-04 00:00:00,Standard Class,84995,5
9970,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,390.302725,DH-13075,Dave Hallsten,Corporate,Spain,NaN,NaN,NaN,NaN,CA-2015-159534,2019-03-20,2019-03-23 00:00:00,First Class,1087936,8

In [44]:
df_global["Volumen_Venta"] = df_global["Cantidad"] * df_global["Precio unitario"]
df_global["Año_compra"] = df_global["Fecha compra"].dt.year
df_global["Beneficio"] = df_global["Volumen_Venta"] - df_global["Coste Producción"]

In [55]:
url = "https://en.wikipedia.org/wiki/List_of_countries_by_average_wage"
r = requests.get(url)
df_list = pd.read_html(r.text)
df=df_list[1]
df

C:\Users\fedec\AppData\Local\Temp\ipykernel_20592\2132445449.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_list = pd.read_html(r.text)

,Country,"Gross Average Monthly Wages (USD, at current exchange rates)[4]",Year
0,Switzerland *,8111,2022
1,Luxembourg *,6633,2022
2,United States *,6455,2022
3,Iceland *,6778,2023
4,Norway *,5665,2022
5,Denmark *,5642,2022
6,Canada *,5081,2022
7,Ireland *,4642,2022
8,Netherlands *,4581,2022
9,Belgium *,4560,2022
10,Austria *,4312,2022
11,United Kingdom *,4179,2022
12,Finland *,4090,2022
13,Germany *,3984,2022
14,Sweden *,3977,2022
15,France *,3655,2022
16,Israel *,3507,2023
17,Italy *,2763,2022
18,Slovenia *,2611,2022
19,Spain *,2551,2022
20,Cyprus *,2316,2022
21,Portugal *,1781,2022
22,Estonia *,1981,2023
23,Czech Republic *,1770,2022
24,Lithuania *,2173,2023
25,Slovakia *,1512,2022
26,Greece *,1417,2022
27,Poland *,1416,2022
28,Croatia *,1713,2023
29,Romania *,1610,2023
30,Latvia *,1662,2023
31,Serbia *,1252,2024
32,Hungary *,1189,2022
33,Bulgaria *,1113,2023
34,Montenegro *,1067,2023
35,Bosnia and Herzegovina *,1077,2023
36,North Macedonia *,965,2023
37,Kazakhstan *,673,2022
38,Belarus *,621,2022
39,Armenia *,689,2023
40,Georgia *,707,2023
41,Turkey *,607,2023
42,Moldova *,553,2022
43,Azerbaijan *,494,2022
44,Ukraine *,430,2020
45,Albania *,701,2023
46,Uzbekistan *,351,2022
47,Kyrgyzstan *,316,2022

In [59]:
df_renta=df.rename(columns={"Country":"País",	"Gross Average Monthly Wages (USD, at current exchange rates)[4]":"Sueldo Mensual USD RPC",	"Year":"Año"})

In [61]:
df_renta= df_renta.drop(columns=["Año"])

In [63]:
df_renta["País"] = df_renta["País"].str.replace(r'[$,*]','',regex = True)
df_renta["País"] = df_renta["País"].str.strip()
df_global["País"] = df_global["País"].str.strip()

In [65]:
##se agrega el sueldo mensual de renta per capita en caso de querer buscar correlaciones 
df_global = df_global.merge(df_renta, on= "País",how="left")
df_global

,ID Producto,Categoría,Sub-categoría,Nombre Producto,Coste Producción,ID Cliente,Nombre cliente,Segmento,País,Ciudad,...,ID Pedido,Fecha compra,Fecha envío,Modo envío,Precio unitario,Cantidad,Volumen_Venta,Año_compra,Beneficio,Sueldo Mensual USD RPC
0,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,230.098156,CG-12520,Claire Gute,Consumer,United States,Henderson,...,CA-2016-152156,2020-11-08,2020-11-11 05:00:00,Second Class,26196,2,52392,2020,5.216190e+04,6455
1,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,230.098156,AG-10900,Arthur Gainer,Consumer,United States,Tucson,...,CA-2017-110198,2021-05-01,2021-05-02 00:00:00,First Class,314352,3,943056,2021,9.428259e+05,6455
2,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,230.098156,SV-20365,Seth Vernon,Consumer,United States,Dover,...,CA-2017-159793,2021-08-25,2021-08-29 00:00:00,Standard Class,13098,2,26196,2021,2.596590e+04,6455
3,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,230.098156,HF-14995,Herbert Flentye,Consumer,Germany,NaN,...,CA-2016-117681,2020-04-09,2020-04-14 00:00:00,Standard Class,556665,5,2783325,2020,2.783095e+06,3984
4,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",563.102730,CG-12520,Claire Gute,Consumer,United States,Henderson,...,CA-2016-152156,2020-11-08,2020-11-11 00:00:00,Second Class,73194,3,219582,2020,2.190189e+05,6455
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9966,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,390.302725,KF-16285,Karen Ferguson,Home Office,Spain,NaN,...,US-2017-148362,2021-07-01,2021-07-08 00:00:00,Standard Class,16999,1,16999,2021,1.660870e+04,2551
9967,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,390.302725,GM-14695,Greg Maxwell,Corporate,Spain,NaN,...,CA-2016-100244,2020-09-20,2020-09-24 00:00:00,Standard Class,271984,2,543968,2020,5.435777e+05,2551
9968,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,390.302725,CM-12235,Chris McAfee,Consumer,Spain,NaN,...,CA-2016-144309,2020-12-10,2020-12-16 00:00:00,Standard Class,67996,5,339980,2020,3.395897e+05,2551
9969,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,390.302725,LB-16795,Laurel Beltran,Home Office,Spain,NaN,...,CA-2017-147032,2021-07-31,2021-08-04 00:00:00,Standard Class,84995,5,424975,2021,4.245847e+05,2551
9970,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,390.302725,DH-13075,Dave Hallsten,Corporate,Spain,NaN,...,CA-2015-159534,2019-03-20,2019-03-23 00:00:00,First Class,1087936,8,8703488,2019,8.703098e+06,2551

In [69]:
df_global.to_csv('C:/Users/fedec/OneDrive/Desktop/contenido/py/DS/CASO PRÁCTICO 1/Practica-creo-Dataset/ventas_globales.csv', index=False)